name: Weekly F1 Scraper Automation

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight UTC
  workflow_dispatch: # allows manual trigger from GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Drivers Standings Scraper
        run: python web_scraping/drivers_standing.py

      - name: Run Teams Standings Scraper
        run: python web_scraping/teams_standing.py

      - name: Commit and push scraped data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add scraped_data/*.json
          git commit -m "Weekly F1 data update [skip ci]" || echo "No changes to commit"
          git push
